<a href="https://colab.research.google.com/github/varasrisiri/Machine-Learning-Course_Part-1/blob/main/9_Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numerical Python

Advantages of Numpy Arrays:
1. Allows several Mathematical Operations
2. Faster Operations

In [1]:
import numpy as np

#List vs Numpy -- Time Taken

In [2]:
from time import process_time

#Time taken by a list

In [8]:
python_list = [i for i in range(500)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.00012160900000024455


In [7]:
np_array = np.array([i for i in range(500)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

9.574099999998253e-05


#Numpy Arrays

In [9]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [12]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [15]:
# creating a 1 dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [16]:
a.shape

(4,)

In [17]:
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
b.shape

(2, 4)

In [19]:
c = np.array([(1,2,3,4), (5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#Initial Placeholders in numpy arrays


In [20]:
#create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
#array of a particular value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [26]:
# create an identity matrix --> have no. of rows = no. of columns
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
#create a numpy array with random values
b = np.random.random((3,5))
print(b)

[[0.79972432 0.24069076 0.94420842 0.36908919 0.97688888]
 [0.85248083 0.30387823 0.14471337 0.93752974 0.46696876]
 [0.10594768 0.03654308 0.77221091 0.40050693 0.31885704]]


In [29]:
#create a random interger values array with in a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[86 29 93 73 27]
 [40 16 31 66 81]
 [92 31 65 77 97]]


In [38]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,6) #here 6 is mentioning no. of values required between 10 to 30
print(d)

[10. 14. 18. 22. 26. 30.]


In [37]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5) # here 5 is mentioning the gap between the numbers
print(e)

[10 15 20 25]


In [41]:
# convert a list to a numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [42]:
# convert a tuple to a numpy array
tuple1 = (10,20,30,40,50)

np_array = np.array(tuple1)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

#Analyzing a  numpy array

In [43]:
c = np.random.randint(10,90,(5,5))
print(c)

[[72 84 83 35 71]
 [35 63 73 21 15]
 [19 77 71 15 12]
 [46 64 23 27 59]
 [83 20 41 24 59]]


In [44]:
#array dimension
print(c.shape)

(5, 5)


In [46]:
# number of dimensions
print(c.ndim)

2


In [47]:
# number of elements in an array
print(c.size)

25


In [48]:
#checking the data type of the values in the array
print(c.dtype)

int64


#Mathematical operations on a np array

In [50]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)  #concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [52]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[1 4 8]
 [9 3 3]
 [8 2 9]]
[[16 10 19]
 [18 19 14]
 [17 18 19]]


In [54]:
print(a+b)  ## incase of numpy array we have element wise mathematical operations
print(a-b)
print(a*b)
print(a/b)

[[17 14 27]
 [27 22 17]
 [25 20 28]]
[[-15  -6 -11]
 [ -9 -16 -11]
 [ -9 -16 -10]]
[[ 16  40 152]
 [162  57  42]
 [136  36 171]]
[[0.0625     0.4        0.42105263]
 [0.5        0.15789474 0.21428571]
 [0.47058824 0.11111111 0.47368421]]


In [55]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)


[[4 4 5]
 [4 2 1]
 [4 5 3]]
[[13 13 10]
 [12 18 10]
 [14 11 10]]


In [57]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 17 15]
 [16 20 11]
 [18 16 13]]
[[ -9  -9  -5]
 [ -8 -16  -9]
 [-10  -6  -7]]
[[52 52 50]
 [48 36 10]
 [56 55 30]]
[[0.30769231 0.30769231 0.5       ]
 [0.33333333 0.11111111 0.1       ]
 [0.28571429 0.45454545 0.3       ]]


#Array Manipulation

In [60]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 1 0]
 [1 2 5]]
(2, 3)


In [59]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 3]
 [5 0]
 [4 8]]
(3, 2)


In [61]:
## Example 2
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 2 8]
 [1 5 2]]
(2, 3)


In [62]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 1]
 [2 5]
 [8 2]]
(3, 2)


#Reshaping a array

In [63]:
a = np.random.randint(0,10,(3,4))
print(a)
print(a.shape)

[[7 8 3 7]
 [9 0 9 1]
 [3 0 4 0]]
(3, 4)


In [64]:
b = a.reshape(4,3)
print(b)
print(b.shape)

[[7 8 3]
 [7 9 0]
 [9 1 3]
 [0 4 0]]
(4, 3)
